/*
SQLyog Ultimate v12.5.1 (64 bit)
MySQL - 10.4.22-MariaDB-log : Database - db_pengaduan
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`db_pengaduan` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `db_pengaduan`;

/*Table structure for table `m_help_pengadu` */

DROP TABLE IF EXISTS `m_help_pengadu`;

CREATE TABLE `m_help_pengadu` (
  `id` varchar(10) NOT NULL,
  `nama` varchar(255) DEFAULT NULL,
  `alamat` varchar(255) DEFAULT NULL,
  `telepon` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `m_help_pengadu` */

insert  into `m_help_pengadu`(`id`,`nama`,`alamat`,`telepon`,`email`) values 
('P00001','Maria Christina Hartono','Jl. Danau Tamblingan V / 14, Taman Griya Jimbaran','085646925270','mariachristinahartono@gmail.com'),
('P00002','Christina','Jimbaran','085646925270','mariachristinahartono@gmail.com'),
('P00003','Benita','Denpasar','085646928097','prognetkelompok3@gmail.com'),
('P00004','Yoga Dharma','Klungkung','085646925270','prognetkelompok3@gmail.com'),
('P00005','Krisna','Jimbaran','085646925270','prognetkelompok3@gmail.com'),
('P00006','Maria','Denpasar','085646925270','mariachristinahartono@gmail.com'),
('P00007','Maria Christina Hartono','Denpasar','085646925270','mariachristinahartono@gmail.com');

/*Table structure for table `m_jenis_aduan` */

DROP TABLE IF EXISTS `m_jenis_aduan`;

CREATE TABLE `m_jenis_aduan` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `jenis_aduan` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

/*Data for the table `m_jenis_aduan` */

insert  into `m_jenis_aduan`(`id`,`jenis_aduan`,`created_at`,`updated_at`) values 
(1,'layanan','2022-12-17 21:24:35','2022-12-17 21:24:42'),
(2,'biaya','2022-12-17 21:24:57','2022-12-17 21:25:01'),
(3,'fasilitas','2022-12-17 21:25:12','2022-12-17 21:25:15');

/*Table structure for table `m_pegawai` */

DROP TABLE IF EXISTS `m_pegawai`;

CREATE TABLE `m_pegawai` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `kode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'entry',
  `username` varchar(50) DEFAULT NULL,
  `no_induk` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `absen_id` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kode_bpjs` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `nama` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `nama_tercetak` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gelar_depan` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gelar_belakang` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_pegawai_id` tinyint(4) DEFAULT NULL COMMENT 'm_statuspegawai',
  `jenis_profesi_id` int(11) DEFAULT NULL COMMENT 'm_jenis_profesi',
  `spesialisasi_id` smallint(6) DEFAULT NULL COMMENT 'm_spesialisasi',
  `sub_spesialisasi_id` int(10) unsigned DEFAULT NULL COMMENT 'm_subspesialisasi',
  `qualifikasi_id` int(10) unsigned DEFAULT NULL COMMENT 'm_kualifikasi',
  `pendidikan_terakhir_id` int(11) DEFAULT NULL COMMENT 'm_riwayat_pendidikan',
  `jabatan_fungsional_terakhir` int(11) DEFAULT NULL COMMENT 'm_riwayat_fungsional',
  `jabatan_struktural_id` int(11) DEFAULT NULL COMMENT 'm_riwayat_struktural',
  `unit_id` int(11) DEFAULT NULL COMMENT '(tidak dipakai (m_subunit_dokter))diambil id unit dari riwayat mutasi',
  `subunit_id` int(11) DEFAULT NULL COMMENT '(tidak dipakai (m_subunit_dokter))diambil id unit dari riwayat mutasi',
  `tempat_lahir` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `tanggal_lahir` date DEFAULT NULL COMMENT 'entry',
  `jeniskelamin_id` int(10) unsigned DEFAULT NULL COMMENT 'm_jenis_kelamin',
  `agama_id` int(10) unsigned DEFAULT NULL COMMENT 'm_agama',
  `bahasa_aktif_id` smallint(6) DEFAULT NULL COMMENT 'm_bahasaaktif',
  `alamat` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `dusun` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `desa_id` int(11) DEFAULT NULL COMMENT 'm_desa',
  `kecamatan_id` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'm_kecamatan',
  `kabupaten_id` int(11) DEFAULT NULL COMMENT 'm_kabupaten',
  `provinsi_id` int(11) DEFAULT NULL COMMENT 'm_provinsi',
  `kodepos` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `nik` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `npwp` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `file_photo` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `file_ktp` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `file_kk` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `file_npwp` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'entry',
  `status_nikah_id` tinyint(4) DEFAULT NULL COMMENT 'm_statusnikah',
  `status_daftar_id` tinyint(4) DEFAULT NULL COMMENT '1= Terdaftar di Balimed; 2=Tidak Terdaftar',
  `created_at` timestamp NULL DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `sso_user_id` int(11) DEFAULT NULL COMMENT 'sso',
  `passcode` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'm_passcode',
  `valid_until` datetime DEFAULT NULL COMMENT 'masa berlaku passcode',
  PRIMARY KEY (`id`),
  KEY `spesialisasi_id` (`spesialisasi_id`),
  KEY `sub_spesialisasi_id` (`sub_spesialisasi_id`),
  KEY `qualifikasi_id` (`qualifikasi_id`),
  KEY `pendidikan_id` (`pendidikan_terakhir_id`),
  KEY `m_pegawai_ibfk_6` (`jeniskelamin_id`),
  KEY `agama_id` (`agama_id`),
  KEY `bahasa_aktif_id` (`bahasa_aktif_id`)
) ENGINE=InnoDB AUTO_INCREMENT=480 DEFAULT CHARSET=utf8mb4;

/*Data for the table `m_pegawai` */

insert  into `m_pegawai`(`id`,`kode`,`username`,`no_induk`,`absen_id`,`kode_bpjs`,`nama`,`nama_tercetak`,`gelar_depan`,`gelar_belakang`,`status_pegawai_id`,`jenis_profesi_id`,`spesialisasi_id`,`sub_spesialisasi_id`,`qualifikasi_id`,`pendidikan_terakhir_id`,`jabatan_fungsional_terakhir`,`jabatan_struktural_id`,`unit_id`,`subunit_id`,`tempat_lahir`,`tanggal_lahir`,`jeniskelamin_id`,`agama_id`,`bahasa_aktif_id`,`alamat`,`dusun`,`desa_id`,`kecamatan_id`,`kabupaten_id`,`provinsi_id`,`kodepos`,`nik`,`npwp`,`file_photo`,`file_ktp`,`file_kk`,`file_npwp`,`status_nikah_id`,`status_daftar_id`,`created_at`,`created_by`,`updated_at`,`updated_by`,`deleted_at`,`sso_user_id`,`passcode`,`valid_until`) values 
(2,'MADE','made','23',NULL,'BPJSMADE','Made',NULL,NULL,NULL,2,5,1,1,1,1,NULL,NULL,1,1,'Badung','2022-10-21',1,4,1,'Kampial','Kampial',1,'1',1,1,'80361','0','5100000000000000',NULL,NULL,NULL,NULL,2,1,'2022-10-21 14:58:24',NULL,'2023-01-09 13:37:09',NULL,'2023-01-07 00:32:23',12345,NULL,NULL),
(137,'1','wirya','1',NULL,NULL,'DR. dr.Gede Wirya Kusuma Duarsa,SpU',NULL,NULL,NULL,1,5,NULL,NULL,NULL,1,NULL,1,NULL,NULL,'DALUNG','2023-01-01',1,4,1,'dalung',NULL,NULL,NULL,NULL,NULL,NULL,'12134121513453',NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,'2023-01-09 08:04:21',NULL,NULL,13579,NULL,NULL),
(138,'2',NULL,'1',NULL,NULL,'DR.dr.A.A. Oka,SpU',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-07 07:00:02',NULL,'2023-01-07 07:00:02',NULL,NULL,NULL),
(139,'3',NULL,'1',NULL,NULL,'dr. Ketut Wiargitha, SpB',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-07 07:43:09',NULL,'2023-01-07 07:43:09',NULL,NULL,NULL),
(140,'4',NULL,'1',NULL,NULL,'dr. Made Yanti Indriyani , Sp.B',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-07 07:49:44',NULL,'2023-01-07 07:49:44',NULL,NULL,NULL),
(141,'5',NULL,'1',NULL,NULL,'dr. Ni Putu Yenny Kendarini, SpB',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-07 09:44:00',NULL,'2023-01-07 09:44:00',NULL,NULL,NULL),
(142,'6',NULL,NULL,NULL,NULL,'dr. AA Gde Ngurah Asmarajaya, SpB, SpBP',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-09 23:14:33',NULL,'2023-01-09 23:14:33',NULL,NULL,NULL),
(143,'7',NULL,NULL,NULL,NULL,'dr.K.G.Mulyadi Ridia , Sp.OT(K)',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-09 23:19:15',NULL,'2023-01-09 23:19:15',NULL,NULL,NULL),
(144,'8',NULL,NULL,NULL,NULL,'dr.D.G.Kurnia Pratama , Sp.OT',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(145,'9',NULL,NULL,NULL,NULL,'Prof. Dr dr Putu Astawa, SpBO (K ),M.Kes, FICS',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-28 04:25:31',NULL,NULL,NULL,NULL,NULL),
(146,'10',NULL,NULL,NULL,NULL,'dr. I Gusti Lanang NA Arta Wiguna, SpOT',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(147,'11',NULL,NULL,NULL,NULL,'dr. AA Gde Yuda Asmara,SpOT',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(148,'12',NULL,NULL,NULL,NULL,'dr. Subagia, SpB',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(149,'13',NULL,NULL,NULL,NULL,'dr. Made Yanti Indriyani , Sp.B',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(150,'14',NULL,NULL,NULL,NULL,'DR.dr. KP Yasa, SpB, SpBTKV',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(151,'15',NULL,NULL,NULL,NULL,'dr. Ketut Sudhartana, SpB - KBD',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(152,'16',NULL,NULL,NULL,NULL,'Nena Mawarsari, Psikologi Klinik',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(153,'17',NULL,NULL,NULL,NULL,'dr. Wayan Sudhana, SpPD, KGH',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(154,'18',NULL,NULL,NULL,NULL,'dr. Putu Lia Paramita, SpB',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(155,'19',NULL,NULL,NULL,NULL,'Prof.DR.dr Made Sri Maliawan, SpBS (K)',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(156,'20',NULL,NULL,NULL,NULL,'dr. A.A.Gde Agung Anom Ari Wiradana, SpB',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(157,'21',NULL,NULL,NULL,NULL,'dr. Purna Putra, SpS',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(158,'22',NULL,NULL,NULL,NULL,'dr. Maryadi,SpPD-KGEH',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(159,'23',NULL,NULL,NULL,NULL,'dr. Ida Bagus Mahendra, SpPD, KGH',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(160,'24',NULL,NULL,NULL,NULL,'dr. I Made Duwi Sumohadi, SpPD, KHOM,FINASIM',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(161,'25',NULL,NULL,NULL,NULL,'dr.Putri Eka Pradnyaning,Sp.N',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(162,'26',NULL,NULL,NULL,NULL,'dr.Prayuda, SpPD',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(163,'27',NULL,NULL,NULL,NULL,'Nena Mawarsari, Psikologi Klinik',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(164,'28',NULL,NULL,NULL,NULL,'dr. Made Gandhi Mahardika , M.Biomed , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(165,'29',NULL,NULL,NULL,NULL,'dr. I Kadek Sukamertha , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(166,'30',NULL,NULL,NULL,NULL,'dr. Ni G.A.A.S.M. Puspawaty Wetan , Sp.OG (K)',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(167,'31',NULL,NULL,NULL,NULL,'dr. Gede Wirakusuma , M.Biomed , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(168,'32',NULL,NULL,NULL,NULL,'dr. Bagus Ngurah Brahmantara, M.Biomed , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(169,'33',NULL,NULL,NULL,NULL,'dr. A.A.Ayu Konsita Wardani , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(170,'34',NULL,NULL,NULL,NULL,'dr. A.A.N.M.Agung Putra Wirawan , Sp.OG ',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(171,'35',NULL,NULL,NULL,NULL,'dr. Wayan Sumardhi , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(172,'36',NULL,NULL,NULL,NULL,'dr. Ida Ayu Andayani , Sp.OG (K)',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(173,'37',NULL,NULL,NULL,NULL,'dr. Putu Darma Kusuma Ipik, Sp.OG ',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(174,'38',NULL,NULL,NULL,NULL,'dr. A.A.Ayu Konsita Wardani , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(175,'39',NULL,NULL,NULL,NULL,'dr. Ni G.A.A.S.M. Puspawaty Wetan , Sp.OG (K)',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(176,'40',NULL,NULL,NULL,NULL,'dr. Made Gandhi Mahardika , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(177,'41',NULL,NULL,NULL,NULL,'dr. Geg Mas Nurcahya Dewi, Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(178,'42',NULL,NULL,NULL,NULL,'dr. I Gusti Putu Mayun Mayura , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(179,'43',NULL,NULL,NULL,NULL,'dr. I Gde Sastra Winata , M.Biomed, Sp.OG (K)',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(180,'44',NULL,NULL,NULL,NULL,'dr. Angga Diningrat , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(181,'45',NULL,NULL,NULL,NULL,'Prof Dr dr DN Wibawa, SpPD-KGEH',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(182,'46',NULL,NULL,NULL,NULL,'Prof. dr. Ketut Niti Susila, SpM',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(183,'47',NULL,NULL,NULL,NULL,'dr. AAA Sukartini Djelantik, SpM',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(185,'49',NULL,NULL,NULL,NULL,'dr. Putu Budhiastra, SpM',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(186,'50',NULL,NULL,NULL,NULL,'dr. Wayan Gede Jaya Negara, SpM',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(187,'51',NULL,NULL,NULL,NULL,'dr.Sari Marina , SpM',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(188,'52',NULL,NULL,NULL,NULL,'dr.Luh Putu Intan Kartika Chandra Dewi , SpM',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(189,'53',NULL,NULL,NULL,NULL,'dr.Ni Nyoman Triharpini , SpM',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(190,'54',NULL,NULL,NULL,NULL,'dr. Ida Ayu Ary Pramita, SpM',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(191,'55',NULL,NULL,NULL,NULL,'dr. Komang Tridiyoga. SpM',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(192,'56',NULL,NULL,NULL,NULL,'Prof.DR.dr.IBN Rai, SpP(K)',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(193,'57',NULL,NULL,NULL,NULL,'dr. Oliva , SpJP',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(194,'58',NULL,NULL,NULL,NULL,'dr. Rani Maliawan , M.Biomed, SpJP',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(195,'59',NULL,NULL,NULL,NULL,'dr.Beny Surya Wijaya,M.Biomed,Sp.PD',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(196,'60',NULL,NULL,NULL,NULL,'dr. I Made Pande Dwipayana,Sp.PD, KEMD,FINASIM',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(197,'61',NULL,NULL,NULL,NULL,'dr, Prayuda , Sp.PD',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(198,'62',NULL,NULL,NULL,NULL,'Dr. Alit Aryani, Sp.KJ',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(199,'63',NULL,NULL,NULL,NULL,'dr. Ketut Bajra Nadha, SpJP',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(200,'64',NULL,NULL,NULL,NULL,'dr.Hendy Wirawan, M.BioMed, SpJP FIHA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(201,'65',NULL,NULL,NULL,NULL,'dr. Putu Primeriana Nugiaswari , SpJP',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(202,'66',NULL,NULL,NULL,NULL,'dr. I Made Pande Dwipayana,Sp.PD, KEMD,FINASIM',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(203,'67',NULL,NULL,NULL,NULL,'dr.Prayuda,Sp.PD',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(204,'68',NULL,NULL,NULL,NULL,'dr. I Made Intaran, SpTHT - KL',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(205,'69',NULL,NULL,NULL,NULL,'dr. Sari Wulan Dwi Sutanegara, SpTHT - KL',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(206,'70',NULL,NULL,NULL,NULL,'dr. Komang Andi Dwi Saputra,Sp.THT-KL',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(207,'71',NULL,NULL,NULL,NULL,'dr. A.A.Putu Adi Rusdika , Sp.THT-KL',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(208,'72',NULL,NULL,NULL,NULL,'dr. Ade Ari Sutradewi, SpTHT-KL',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(209,'73',NULL,NULL,NULL,NULL,'dr. Putu Dian Ariyanti Putri, SpTHT-KL',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(210,'75',NULL,NULL,NULL,NULL,'dr. Christina Kurniasih, SpTHT-KL',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(211,'76',NULL,NULL,NULL,NULL,'dr. Ida Bagus Semara Putra, SpTHT-KL',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(212,'77',NULL,NULL,NULL,NULL,'dr A.A. Ngurah Rahma Putra SpTHT-KL ',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(213,'78',NULL,NULL,NULL,NULL,'dr. I Gusti Ketut Nurada SpTHT-KL (K)',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(214,'79',NULL,NULL,NULL,NULL,'dr. Dewa Made Sudiatmika, SpTHT-KL (K)',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(215,'80',NULL,NULL,NULL,NULL,'dr. I Kompiang Gd Suandi, SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(216,'81',NULL,NULL,NULL,NULL,'dr. Ni Putu Arniyati, SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(217,'82',NULL,NULL,NULL,NULL,'dr.Ayu Ketut Surya Dewi, M.Biomed, SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(218,'83',NULL,NULL,NULL,NULL,'dr. Nyoman Metriani Nesa , MSc , SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(219,'84',NULL,NULL,NULL,NULL,'dr. IB Agung Winaya , Sp A',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(220,'85',NULL,NULL,NULL,NULL,'dr.A.A. Widnyana, Sp.A',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(221,'86',NULL,NULL,NULL,NULL,'dr.Bagus Ngurah Mahakrishna , Sp.A',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(222,'87',NULL,NULL,NULL,NULL,'dr. I Kompiang Gd Suandi, SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(223,'88',NULL,NULL,NULL,NULL,'dr. Kompiang Gautama, SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(224,'90',NULL,NULL,NULL,NULL,'dr.I Nyoman Budi Hartawan,MSc , SpA (K)',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(225,'91',NULL,NULL,NULL,NULL,'dr.A.A. Widnyana, Sp.A',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(226,'93',NULL,NULL,NULL,NULL,'dr.Mas Vina, SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(227,'94',NULL,NULL,NULL,NULL,'dr.Ayu Ketut Surya Dewi, M.Biomed, SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(228,'95',NULL,NULL,NULL,NULL,'dr.Bagus Ngurah Mahakrishna , SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(229,'96',NULL,NULL,NULL,NULL,'dr.A.A. Tri Yuliantini , Sp.A',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(230,'97',NULL,NULL,NULL,NULL,'dr. IB Agung Winaya , Sp A',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(231,'98',NULL,NULL,NULL,NULL,'dr. Ni Putu Arniyati, SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(232,'99',NULL,NULL,NULL,NULL,'dr.Mas Vina, SpA',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(233,'100',NULL,NULL,NULL,NULL,'dr.Agus Suryawan, M.BioMed, MSpS',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(234,'101',NULL,NULL,NULL,NULL,'dr. Kumaratini, SpS',NULL,NULL,NULL,2,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(235,'102',NULL,NULL,NULL,NULL,'dr. Purna Putra , SpS',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(236,'103',NULL,NULL,NULL,NULL,'dr. I A Sri Indrayani , SpS',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(237,'104',NULL,NULL,NULL,NULL,'dr. Bagus Ngurah Mahasena Putera A , Sp.N',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(238,'105',NULL,NULL,NULL,NULL,'dr. Putu Yudhi Nusartha Diputra , Sp.N',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(239,'106',NULL,NULL,NULL,NULL,'dr.A.A. Tri Yuliantini , Sp.A',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(240,'107',NULL,NULL,NULL,NULL,'dr. I Made Oka Asmara Jaya, Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(241,'108',NULL,NULL,NULL,NULL,'dr. I Made Ariyana , Sp.OG (K)',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(242,'109',NULL,NULL,NULL,NULL,'dr. Desak Nyoman Praptini, Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(243,'110',NULL,NULL,NULL,NULL,'dr. I Kadek Sukamertha , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(244,'111',NULL,NULL,NULL,NULL,'dr. Fido Anggli , M.Biomed , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(245,'112',NULL,NULL,NULL,NULL,'dr. Made Bagus Dwi Aryana , Sp.OG (K)',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(246,'113',NULL,NULL,NULL,NULL,'dr. A.A.Ayu Konsita Wardani , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(247,'114',NULL,NULL,NULL,NULL,'dr. Gede Wirakusuma , M.Biomed , Sp.OG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(248,'115',NULL,NULL,NULL,NULL,'drg. Made Suthanaya, SpBM',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(249,'116',NULL,NULL,NULL,NULL,'drg. Agus Gede Sutamaya,Sp.Perio',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(250,'117',NULL,NULL,NULL,NULL,'drg. Irayanti',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(251,'118',NULL,NULL,NULL,NULL,'drg.A.A.Istri Mas Indrawati',NULL,NULL,NULL,11,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(252,'119',NULL,NULL,NULL,NULL,'drg. Shirley Indrajaya , SKG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(253,'120',NULL,NULL,NULL,NULL,'drg. Desi Lastya Utami',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(254,'121',NULL,NULL,NULL,NULL,'drg. Nyoman Sri Wirastuti',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(255,'122',NULL,NULL,NULL,NULL,'drg. I Putu Arna Suputra',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(256,'123',NULL,NULL,NULL,NULL,'drg. Ni Made Titia Prabandari Iswara',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(257,'124',NULL,NULL,NULL,NULL,'dr. A.A.S. Putra Dewi, SpKK',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(258,'125',NULL,NULL,NULL,NULL,'dr. IGAA Dwi Karmila, SpKK',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(259,'126',NULL,NULL,NULL,NULL,'dr. Yukhi Kurniawan, Sp.And',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(260,'127',NULL,NULL,NULL,NULL,'dr. I Wayan Gede Sutadarma , M Gizi , SpKG',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(261,'128',NULL,NULL,NULL,NULL,'dr. Kumara Tini , SpS , FINS',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(262,'129',NULL,NULL,NULL,NULL,'dr.Agus Suryawan, M.BioMed, MSpS',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(263,'130',NULL,NULL,NULL,NULL,'dr. Oka Suliani, SpS',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(264,'131',NULL,NULL,NULL,NULL,'dr. IB  Putu Putrawan,SpPD',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(265,'132',NULL,NULL,NULL,NULL,'dr. I Putu Arya Dharma , Sp.B(K)Onk ',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(266,'133',NULL,NULL,NULL,NULL,'dr. I G P Hendra Sanjaya , SpBP - RE',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(267,'134',NULL,NULL,NULL,NULL,'dr.Dewa Putu Wisnu Wardana, SpBS',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(268,'135',NULL,NULL,NULL,NULL,'dr. Belly Sutrisna, SpKJ',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(269,'136',NULL,NULL,NULL,NULL,'dr. Ketut Wiargita , SpB',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(270,'137',NULL,NULL,NULL,NULL,'Prof.Dr.dr.Suastika, SpPD KEMD',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(271,'138',NULL,NULL,NULL,NULL,'dr.Tuty Kuswardhani,SpPD-Kger',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(272,'139',NULL,NULL,NULL,NULL,'dr. I Made Pande Dwipayana,Sp.PD, KEMD,FINASIM',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(273,'140',NULL,NULL,NULL,NULL,'dr.  A.A.Sri Kandyawati, Sp.KFR',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(274,'141',NULL,NULL,NULL,NULL,'dr. Pande Made Murniari Danun, Sp.KFR',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(275,'143',NULL,NULL,NULL,NULL,'dr. Tanjung Subrata',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(392,'tes',NULL,NULL,NULL,NULL,'tes',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-10-28 05:41:11',38,'2022-10-28 05:41:11',38,NULL,NULL,NULL,NULL),
(393,'test',NULL,NULL,NULL,NULL,'dr.cobaan',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,4,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(394,'JOHN',NULL,'01010101','1','BPJSJOHN','dr. John. SpS SpPD Sp.B(K) Onk','John','dr','s',1,5,2,1,1,1,1,1,1,8,'Bali','2022-11-07',1,1,1,'bali','bali',1,'1',1,1,'90290','2938923829','29382938293',NULL,NULL,NULL,NULL,1,1,'2022-11-07 11:23:44',NULL,NULL,NULL,NULL,38,NULL,NULL),
(395,'PROF',NULL,'89189189','1','PROF','Prof. Dr.',NULL,NULL,NULL,1,5,2,1,1,1,1,1,1,8,'Bali','2022-11-07',1,1,1,'bali','bali',1,'1',1,1,'9822','29892','2892',NULL,NULL,NULL,NULL,1,1,'2022-11-09 16:30:26',NULL,NULL,NULL,NULL,2,NULL,NULL),
(396,'TES',NULL,'01010101','1','TES','dr. Made THT',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(397,'MATA',NULL,'78278728','1','MATA','dr. Ketut Mata','Mata',NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(398,'SARF',NULL,'88983933','1','SRF','dr. Putu Saraf','Saraf',NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(399,'Kan',NULL,'08198191','9','KAN','dr. Wayan Kandungan',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(400,'LKJS',NULL,'09290222','8','UMUM','dr. Nyoman Umum',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(401,'JANT',NULL,NULL,NULL,NULL,'dr. Jantung',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(402,'JANTT',NULL,'98234982',NULL,NULL,'dr. Wayan Jantung',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(403,'PER',NULL,'0819811','2','PER','Jon Perawat',NULL,NULL,NULL,1,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,38,NULL,NULL),
(404,'PER2',NULL,'0898272','3','PER2','Prof Perawat',NULL,NULL,NULL,1,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL),
(405,'WAH',NULL,'289282','82','sk','Perawat Mang wahyu',NULL,NULL,NULL,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,42,NULL,NULL),
(406,'SW',NULL,'289282','1','289282','Pak Suwija',NULL,NULL,NULL,1,7,2,1,1,1,1,1,1,8,'Bali',NULL,1,1,1,NULL,NULL,NULL,NULL,NULL,1,'2452','29892','2892',NULL,NULL,NULL,NULL,1,1,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL),
(408,'2134',NULL,'234','45','56','dr.suranadi',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-14 13:00:34',NULL,'2022-12-15 11:03:37',NULL,NULL,NULL,NULL,NULL),
(409,'1234',NULL,'232','24','3245','Dr dr devan kusuma s.kp.sdm.gfc',NULL,NULL,NULL,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-14 13:07:00',NULL,'2022-12-15 10:45:48',NULL,NULL,NULL,NULL,NULL),
(411,'342',NULL,'345','45','r456','santi',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-15 11:05:16',NULL,'2022-12-15 11:05:16',NULL,NULL,NULL,NULL,NULL),
(419,'3e42',NULL,'3456','35','4567','dr ardi',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-18 13:05:46',NULL,'2022-12-18 13:06:23',NULL,NULL,NULL,NULL,NULL),
(420,'160',NULL,'160','160','BPJS160','Fandy',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-18 17:33:05',NULL,'2022-12-18 17:33:05',NULL,NULL,NULL,NULL,NULL),
(424,'testkode',NULL,NULL,NULL,NULL,'TestNama123',NULL,NULL,NULL,1,5,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-19 09:33:47',NULL,'2022-12-19 09:34:33',NULL,NULL,NULL,NULL,NULL),
(425,'JASHJ',NULL,NULL,NULL,NULL,'Ketut',NULL,NULL,NULL,1,1,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-19 10:48:27',NULL,'2022-12-19 10:48:27',NULL,NULL,NULL,NULL,NULL),
(427,'23467',NULL,'234','24','4rf','bapak piarsa','piarsa','dr','skn',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-19 13:23:00',NULL,'2022-12-19 13:23:40',NULL,NULL,NULL,NULL,NULL),
(428,'21',NULL,'234',NULL,NULL,'Dr Jaya Wardana',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-22 10:18:20',NULL,'2022-12-22 10:18:20',NULL,NULL,NULL,NULL,NULL),
(430,'166',NULL,NULL,NULL,NULL,'Nyoman sotoy',NULL,NULL,NULL,1,5,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2022-12-27 04:29:25',NULL,'2022-12-27 04:31:00',NULL,NULL,NULL,NULL,NULL),
(439,'p001',NULL,NULL,NULL,NULL,'michael',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,0,NULL,1,NULL,NULL,'medan','2001-11-17',1,1,NULL,'ajdska',NULL,NULL,NULL,NULL,NULL,NULL,'127319823',NULL,NULL,NULL,NULL,NULL,1,NULL,'2022-12-30 15:02:50',NULL,'2022-12-30 15:02:50',NULL,NULL,NULL,NULL,NULL),
(442,'p0013',NULL,NULL,NULL,NULL,'michael',NULL,NULL,NULL,5,NULL,NULL,NULL,NULL,1,NULL,1,NULL,NULL,'medan','2001-11-17',1,1,NULL,'medan',NULL,NULL,NULL,NULL,NULL,NULL,'487324213',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-02 02:35:16',NULL,'2023-01-02 02:35:16',NULL,NULL,NULL,NULL,NULL),
(444,'P01232',NULL,NULL,NULL,NULL,'Ricky Marchelino',NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,1,NULL,1,NULL,NULL,'Medan','2001-11-17',1,2,NULL,'medan',NULL,NULL,NULL,NULL,NULL,NULL,'2198310238',NULL,NULL,NULL,NULL,NULL,3,NULL,'2023-01-02 03:30:59',NULL,'2023-01-02 03:31:34',NULL,NULL,NULL,NULL,NULL),
(445,'p00111',NULL,NULL,NULL,NULL,'michael',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,1,NULL,1,NULL,NULL,'medan','2001-11-17',3,2,NULL,'medan',NULL,NULL,NULL,NULL,NULL,NULL,'92189023',NULL,NULL,NULL,NULL,NULL,1,NULL,'2023-01-02 03:34:32',NULL,'2023-01-02 03:34:32',NULL,NULL,NULL,NULL,NULL),
(446,'123',NULL,NULL,NULL,NULL,'Wisnu',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,1,NULL,1,NULL,NULL,'DALUNG','2017-01-03',1,4,NULL,'dalung',NULL,NULL,NULL,NULL,NULL,NULL,'12134121513453',NULL,NULL,NULL,NULL,NULL,1,NULL,'2023-01-07 07:10:25',NULL,'2023-01-07 07:10:25',NULL,NULL,NULL,NULL,NULL),
(447,'12',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-07 11:23:53',NULL,'2023-01-07 11:23:53',NULL,NULL,NULL,NULL,NULL),
(448,'2',NULL,'898989898',NULL,NULL,'dataaa',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-07 11:24:45',NULL,'2023-01-08 08:47:12',NULL,NULL,NULL,NULL,NULL),
(449,'22',NULL,NULL,NULL,NULL,'wisnu',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,1,NULL,1,NULL,NULL,'denpasar','2023-01-07',1,2,NULL,'dalung',NULL,NULL,NULL,NULL,NULL,NULL,'1233',NULL,NULL,NULL,NULL,NULL,4,NULL,'2023-01-07 11:44:18',NULL,'2023-01-07 11:44:18',NULL,NULL,NULL,NULL,NULL),
(450,'112',NULL,'123',NULL,NULL,'purna',NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-07 12:37:09',NULL,'2023-01-07 12:37:09',NULL,NULL,NULL,NULL,NULL),
(451,'123',NULL,'213',NULL,NULL,'asdasf',NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-07 12:49:04',NULL,'2023-01-07 12:49:04',NULL,NULL,NULL,NULL,NULL),
(452,'122',NULL,'121',NULL,NULL,'madekes',NULL,NULL,NULL,5,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-08 08:36:12',NULL,'2023-01-08 09:18:49',NULL,NULL,NULL,NULL,NULL),
(453,'223',NULL,'102',NULL,NULL,'baren',NULL,NULL,NULL,1,1,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-08 09:58:35',NULL,'2023-01-08 09:58:35',NULL,NULL,NULL,NULL,NULL),
(454,'121',NULL,'352',NULL,NULL,'kmade',NULL,NULL,NULL,3,14,16,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-08 11:27:05',NULL,'2023-01-08 11:27:05',NULL,NULL,NULL,NULL,NULL),
(455,'1223',NULL,'123',NULL,NULL,'sama',NULL,NULL,NULL,5,1,19,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-08 11:29:34',NULL,'2023-01-08 11:29:34',NULL,NULL,NULL,NULL,NULL),
(456,'199',NULL,NULL,NULL,NULL,'skorr',NULL,NULL,NULL,NULL,8,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-08 12:43:05',NULL,'2023-01-08 12:43:05',NULL,NULL,NULL,NULL,NULL),
(457,'123123',NULL,'123',NULL,NULL,'kes','made','sd',NULL,5,17,3,17,1,1,NULL,NULL,1,18,'badung',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-09 09:46:19',NULL,'2023-01-09 09:46:19',NULL,NULL,NULL,NULL,NULL),
(458,'332',NULL,'128',NULL,NULL,'bagus','surya','as',NULL,1,1,1,1,1,1,NULL,NULL,1,1,'badung',NULL,1,1,1,'bleleng',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-09 10:21:55',NULL,'2023-01-09 10:21:55',NULL,NULL,NULL,NULL,NULL),
(459,'654',NULL,'333',NULL,NULL,'dava','cuwq','s',NULL,1,1,1,1,1,1,NULL,NULL,1,1,'asd',NULL,1,1,1,'asd','asd',NULL,'1',1,1,'123','123','123',NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-09 12:42:40',NULL,'2023-01-09 12:42:40',NULL,NULL,NULL,NULL,NULL),
(460,'332',NULL,'332',NULL,NULL,'agus','wayan','w',NULL,1,1,1,1,1,1,NULL,NULL,1,1,'badung',NULL,1,1,1,'qwe','qwe',NULL,'1',1,1,'333','333','333',NULL,NULL,NULL,NULL,NULL,NULL,'2023-01-09 12:51:01',NULL,'2023-01-09 12:51:01',NULL,NULL,NULL,NULL,NULL),
(461,'123',NULL,'321',NULL,NULL,'willy','wongka','asd',NULL,1,1,1,1,1,1,NULL,NULL,1,1,'jawa','2023-01-01',1,1,1,'qwe','qwe',NULL,'1',1,1,'21333','213','123',NULL,NULL,NULL,NULL,4,NULL,'2023-01-09 13:31:48',NULL,'2023-01-09 13:33:39',NULL,NULL,NULL,NULL,NULL),
(462,'654',NULL,'123',NULL,NULL,'asd','asd','s',NULL,1,1,1,1,1,1,NULL,NULL,1,1,'badung',NULL,1,1,1,'asd','asd',NULL,'1',1,1,'123','123','123',NULL,NULL,NULL,NULL,1,NULL,'2023-01-09 13:35:14',NULL,'2023-01-09 13:35:14',NULL,NULL,NULL,NULL,NULL),
(463,'332',NULL,'221',NULL,NULL,'nyomanz','nyoman','ss',NULL,1,1,1,1,1,1,NULL,NULL,1,1,'kedonganan','2023-01-09',1,1,1,'jawaa','dsa',NULL,'1',1,1,'232','333','123',NULL,NULL,NULL,NULL,1,NULL,'2023-01-09 14:50:34',NULL,'2023-01-09 14:50:34',NULL,NULL,NULL,NULL,NULL),
(464,'test',NULL,'321',NULL,NULL,'andi','kewer','sa',NULL,1,1,1,1,1,1,NULL,NULL,1,1,'badung','2023-01-04',1,1,1,'jimbaran','sad',NULL,'1',1,1,'1221','1234','1212',NULL,NULL,NULL,NULL,1,NULL,'2023-01-09 14:53:05',NULL,'2023-01-09 14:53:05',NULL,NULL,NULL,NULL,NULL),
(465,'112',NULL,'203',NULL,NULL,'Dewa','dewa','S,pd',NULL,7,18,4,16,3,3,2,NULL,15,14,'Bandung','2023-01-11',1,3,1,'jln sedap mlam','kabang',NULL,'31',8,16,'2324','223423','34235',NULL,NULL,NULL,NULL,2,NULL,'2023-01-10 04:58:08',NULL,'2023-01-10 04:58:08',NULL,NULL,NULL,NULL,NULL),
(468,'001',NULL,'p001',NULL,NULL,'pande',NULL,NULL,NULL,1,1,1,1,1,1,NULL,NULL,1,1,NULL,NULL,1,1,1,NULL,NULL,NULL,'1',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2023-01-10 05:50:07',NULL,'2023-01-10 05:50:07',NULL,NULL,NULL,NULL,NULL),
(469,'2321',NULL,'112',NULL,NULL,'purna','Drs','dasa',NULL,3,17,15,13,2,3,231,NULL,14,17,'Denpasar','2023-01-11',2,3,2,'weqwr','kerjq',NULL,'4',4,18,'32823','2324','34233','scan-0050_page-0001.jpg',NULL,NULL,NULL,2,NULL,'2023-01-10 10:49:56',NULL,'2023-01-10 10:49:56',NULL,NULL,NULL,NULL,NULL),
(470,'002',NULL,'P002',NULL,NULL,'Henri',NULL,NULL,NULL,1,1,1,1,1,1,NULL,NULL,1,1,NULL,NULL,1,1,1,NULL,NULL,NULL,'1',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2023-01-10 11:47:42',NULL,'2023-01-10 11:47:42',NULL,NULL,NULL,NULL,NULL),
(472,'003',NULL,'P003',NULL,NULL,'Kido',NULL,NULL,NULL,1,1,1,1,1,1,NULL,NULL,1,1,NULL,NULL,1,1,1,NULL,NULL,NULL,'1',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2023-01-10 11:56:19',NULL,'2023-01-10 11:56:19',NULL,NULL,NULL,NULL,NULL),
(473,'112',NULL,'234',NULL,NULL,'dataaa','das','s',NULL,2,1,1,1,1,1,2,NULL,1,1,'Denpasar','2023-01-02',1,1,1,'jln sedap mlam','kabang',NULL,'17',1,1,'2324','232','34235','C:\\xampp\\tmp\\php3668.tmp',NULL,NULL,NULL,2,NULL,'2023-01-10 11:59:54',NULL,'2023-01-10 11:59:54',NULL,NULL,NULL,NULL,NULL),
(475,'004',NULL,'P004',NULL,NULL,'Aris',NULL,NULL,NULL,1,1,1,1,1,1,NULL,NULL,1,1,NULL,NULL,1,1,1,NULL,NULL,NULL,'1',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2023-01-10 12:13:11',NULL,'2023-01-10 12:13:11',NULL,NULL,NULL,NULL,NULL),
(476,'222',NULL,'148',NULL,NULL,'baren','serineka','dr','drs',1,1,1,1,1,1,2,NULL,1,1,'karangsem','2023-01-05',1,4,1,'denpasar','kabang',2,'1',1,1,'7878','75767','098098','C:\\xampp\\tmp\\php4E7E.tmp',NULL,NULL,NULL,1,NULL,'2023-01-10 12:08:44',NULL,'2023-01-10 12:11:10',NULL,NULL,NULL,NULL,NULL),
(477,'005',NULL,'P005',NULL,NULL,'Five',NULL,NULL,NULL,1,1,1,1,1,1,NULL,NULL,1,1,NULL,NULL,1,1,1,NULL,NULL,NULL,'1',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2023-01-10 12:17:30',NULL,'2023-01-10 12:17:30',NULL,NULL,NULL,NULL,NULL),
(478,'123',NULL,NULL,NULL,NULL,'Wisnu',NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,1,NULL,1,NULL,NULL,'DALUNG',NULL,1,1,NULL,'dalung',NULL,NULL,NULL,NULL,NULL,NULL,'12134121513453',NULL,NULL,NULL,NULL,NULL,1,NULL,'2023-01-10 12:35:36',NULL,'2023-01-10 12:35:36',NULL,NULL,NULL,NULL,NULL),
(479,'112',NULL,'123',NULL,NULL,'purna','dewa','dr',NULL,2,1,1,1,1,1,3,NULL,1,1,'Bandung','2023-01-04',2,1,1,'denpasar','baledan',NULL,'9',12,1,'2324','2322324223','3242323','C:\\xampp\\tmp\\phpBC8C.tmp',NULL,NULL,NULL,3,NULL,'2023-01-10 13:38:46',NULL,'2023-01-10 13:38:46',NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `t_help_aduan` */

DROP TABLE IF EXISTS `t_help_aduan`;

CREATE TABLE `t_help_aduan` (
  `id` varchar(10) NOT NULL,
  `pengadu_id` varchar(11) DEFAULT NULL,
  `jenis_aduan_id` bigint(20) DEFAULT NULL,
  `tanggal` date DEFAULT NULL,
  `aduan` varchar(255) DEFAULT NULL,
  `aduan_foto` varchar(255) DEFAULT NULL,
  `status_close` tinyint(1) DEFAULT 0,
  `date_create_aduan` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pengadu_id` (`pengadu_id`),
  KEY `jenis_aduan_id` (`jenis_aduan_id`),
  CONSTRAINT `t_help_aduan_ibfk_1` FOREIGN KEY (`pengadu_id`) REFERENCES `m_help_pengadu` (`id`),
  CONSTRAINT `t_help_aduan_ibfk_2` FOREIGN KEY (`jenis_aduan_id`) REFERENCES `m_jenis_aduan` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `t_help_aduan` */

insert  into `t_help_aduan`(`id`,`pengadu_id`,`jenis_aduan_id`,`tanggal`,`aduan`,`aduan_foto`,`status_close`,`date_create_aduan`) values 
('1673844013','P00001',3,'2023-01-05','AC bocor','86a34763cca3dfa5995251dfa6c5a19b.jpg',1,'2023-01-16 12:40:13'),
('1673844377','P00002',3,'2023-01-16','Lantai 1 ada minuman tumpah','cb19d02c6a461389d50fa5623dc2aac3.jpeg',0,'2023-01-16 12:46:17'),
('1673845211','P00003',2,'2023-01-15','Harga obat mahal sekali','eefe9e0209a12f7e725aaf4f12755569.jpg',0,'2023-01-16 13:00:11'),
('1673846575','P00004',1,'2023-01-16','Satpam galak','4df3b14ba6a97b92c7b427719a9a8c6c.jpg',0,'2023-01-16 13:22:55'),
('1673847348','P00005',3,'2023-01-10','Lantai kotor','959bd1cf21cd05680f29080fec4e1b6d.jpeg',0,'2023-01-16 13:35:48'),
('1673865823','P00006',3,'2023-01-16','Lantai kotor','48bfcdefddf172b4a5af61160018c987.jpeg',0,'2023-01-16 18:43:43'),
('1673866495','P00007',3,'2023-01-10','AC bocor','b4a2ecef0cd40ff019e361677915aace.jpg',0,'2023-01-16 18:54:55');

/*Table structure for table `t_help_aduan_respon` */

DROP TABLE IF EXISTS `t_help_aduan_respon`;

CREATE TABLE `t_help_aduan_respon` (
  `id` varchar(10) NOT NULL,
  `aduan_id` varchar(10) DEFAULT NULL,
  `pengadu_id` varchar(10) DEFAULT NULL,
  `pegawai_id` int(10) unsigned DEFAULT NULL,
  `tanggal` datetime DEFAULT NULL,
  `respon` varchar(255) DEFAULT NULL,
  `respon_foto` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `aduan_id` (`aduan_id`),
  KEY `pengadu_id` (`pengadu_id`),
  KEY `pegawai_id` (`pegawai_id`),
  CONSTRAINT `t_help_aduan_respon_ibfk_1` FOREIGN KEY (`aduan_id`) REFERENCES `t_help_aduan` (`id`),
  CONSTRAINT `t_help_aduan_respon_ibfk_2` FOREIGN KEY (`pengadu_id`) REFERENCES `m_help_pengadu` (`id`),
  CONSTRAINT `t_help_aduan_respon_ibfk_3` FOREIGN KEY (`pegawai_id`) REFERENCES `m_pegawai` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `t_help_aduan_respon` */

insert  into `t_help_aduan_respon`(`id`,`aduan_id`,`pengadu_id`,`pegawai_id`,`tanggal`,`respon`,`respon_foto`) values 
('R00001','1673844377',NULL,2,'2023-01-16 12:48:50','Terima kasih atas aduannya, lantai akan segera kami bersihkan',NULL),
('R00002','1673845211',NULL,137,'2023-01-16 13:29:53','Harga obat sudah sesuai standar pabrik',NULL),
('R00003','1673844377',NULL,137,'2023-01-16 13:36:41','Lantai sudah bersih',NULL),
('R00004','1673845211','P00003',NULL,'2023-01-16 13:37:51','Baik terima kasih',NULL),
('R00005','1673866495',NULL,2,'2023-01-16 18:56:41','Terima kasih atas aduan Anda. AC akan kami perbaiki',NULL),
('R00006','1673866495','P00007',NULL,'2023-01-16 18:58:11','Baik, terima kasih',NULL),
('R00007','1673847348',NULL,2,'2023-01-21 14:11:38','Terima kasih atas aduan Anda. Lantai sudah kami bersihkan. Mohon maaf atas ketidaknyamanannya.',NULL),
('R00008','1673844377',NULL,2,'2023-01-21 14:14:09','tes',NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
